[server]
name = "svr04"
listen_addr = "0.0.0.0:22"
host_key_path = "/config/host_key"
history_size = 1000
ssh_version = "SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u3"

[auth]
authorized_keys_dir = "/config/authorized_keys"
accept_any = false
user_db_path = "/config/user.txt"

[[backends]]
name = "cowrie1"
hostname = "cowrie1"
port = 2222
auth_type = "password"
default = true

[[backends]]
name = "cowrie2"
hostname = "cowrie2"
port = 2222
auth_type = "password"
default = false
